[package]
name = "foxdbg-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
foxglove = "0.14.3"
once_cell = { version = "1"}
turbojpeg = "1.3.3"
log = "0.4"
env_logger = "0.11.8"

[build-dependencies]
cbindgen = "0.29.0"
