[package]
name = "foxdbg-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
foxglove = "0.14.3"
once_cell = { version = "1"}

[build-dependencies]
cbindgen = "0.29.0"
